### ISSUE TITLE
要望：ラピスの価格が下がりすぎてるのであげて欲しいです。（2021/01/17 情報追加）

### ISSUE THREAD

**Issue by Merutan** [yurisi0212/SpaceServerIssue#16]
『せめて石炭よりも上でないと入手頻度と価格が一致しません。』  とのこと。  

また、原石の価格も石炭の2分の1になっているところも調整が必要だとのこと。  

まとめ:ラピスラズリ関連のアイテム全ての価格上昇の希望。例(ラピスラズリ原石.ラピスラズリブロック)
希望金額→石炭以上

[『ららりんご』様からのご要望（協議含む）](https://discord.com/channels/366613089694777355/636703086475476992/799846159144583209)

**Comment by yurisi0212** [comment]
少しずつ上昇していきます
