### ISSUE TITLE
要望:トレードの際のラグの改善

### ISSUE THREAD

**Issue by Merutan** [yurisi0212/SpaceServerIssue#23]
トレードに出されたもんが多すぎて開くときに. 秒かかるのをどうかしてほしい

**Comment by yurisi0212** [comment]
ページ分けの必要

**Comment by Merutan** [comment]
1週間売れなかったら返却とかはあかんかな

**Comment by yurisi0212** [comment]
なし

**Comment by Merutan** [comment]
はーい

**Comment by Merutan** [comment]
今、1080？品出品されていて、かなり重い状況のため、重大ラベルを付与して、早急に対応したほうがいいかもしれません。  

開くのに30秒ほどかかりました。

**Comment by Merutan** [comment]
> 要望(意見?)です。
tradeについてですが、出品者が指定した金額(アイテムの売値)の数％を手数料として、出品時に徴収(払わせる)のはどうでしょうか。
これがあれば、不適切(あまりにも高額)な値段の出品を減らすことができるように思われます。  

ぐりんぴーすさんからのご意見です。
