### ISSUE TITLE
バグ：テラコッタに関するShopバグ

### ISSUE THREAD

**Issue by Merutan** [yurisi0212/SpaceServerIssue#27]
・水色と空色のテラコッタの表記が逆  
・空色(実際の色は水色)のテラコッタでの最終確認表 示とチャット欄のITEMSHOPの表示が薄灰色  

[『てんとうもろこし』さんから](https://discord.com/channels/366613089694777355/640133130342367243/802098519807623178)

**Comment by yurisi0212** [comment]
解決
