### ISSUE TITLE
バグ：サーバーに接続時にクライアントに送信するTitleが画面内に入り切らない

### ISSUE THREAD

**Issue by Merutan** [yurisi0212/SpaceServerIssue#35]
[『くりちー』様からのご報告](https://discord.com/channels/366613089694777355/640133130342367243/807234208191086612) 

![image0-2](https://user-images.githubusercontent.com/64207094/107049533-921a6900-680d-11eb-9194-b040e4cc5475.png)

**Comment by yurisi0212** [comment]
仕様です
