### ISSUE TITLE
要望（Discord）：DJロール付与の方法変更

### ISSUE THREAD

**Issue by Merutan** [yurisi0212/SpaceServerIssue#36]
現在、DJロールの付与は手動だと思いますが、これをBotを使って自動化する方が、スタッフの負荷が無くなると思います。  

- 役職パネルv2
- MEE6  
など色々ありますね。  

リアクションを押すと自動付与がいいと思います。
![Screenshot_20210206-012937](https://user-images.githubusercontent.com/64207094/107061135-27702a00-681b-11eb-88c1-fe10dbe9ba1f.png)

**Comment by yurisi0212** [comment]
直接サーバーに関係あるものだけにしてください
