### ISSUE TITLE
バグ: Flyモード中にマグマへ入るとFly判定で自動Kickされる

### ISSUE THREAD

**Issue by Meru7** [yurisi0212/SpaceServerIssue#38]
flyしたままマグマで死ぬと不正な飛行でキックされるそう。  

[『クロ』からのご報告](https://discord.com/channels/366613089694777355/640133130342367243/808124219522809858)

**Comment by Merutan** [comment]
Fry使用中の時ね

**Comment by yurisi0212** [comment]
どんまい
