### ISSUE TITLE
要望（修正案）：Shop - スイカとカボチャのカテゴリーを花から食料に移動する

### ISSUE THREAD

**Issue by Meru7** [yurisi0212/SpaceServerIssue#56]
shopでスイカとカボチャが「花」のカテゴリ内にあるのですが、「食料」の方にあったほうがわかりやすいかなーとのこと。  

[Discord Msg](https://discord.com/channels/366613089694777355/636703086475476992/815571074296053760)

**Comment by yurisi0212** [comment]
ショップはいじりたくないので却下
